# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

#ステータスラインの表示内容強化
[[plugins]]
repo = 'itchyny/lightline.vim'
#----------------------------------------------------------
# ステータスラインの設定
#----------------------------------------------------------

#インデントの可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# ファイルをtree表示してくれる
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''
